# =======================================================================


# Quantum-Enhanced AlphaFold3 Configuration
# Multi-language integration settings

ibm_quantum:
  api_token_env: "IBM_QUANTUM_API_TOKEN"
  base_url: "https://api.quantum.ibm.com/v1"
  backends:
    primary: "ibm_torino"
    secondary: "ibm_brisbane"

  torino:
    qubits: 133
    processor: "Heron r1"
    queue_length: 722
    recommended_for: ["small_proteins", "algorithm_testing"]

  brisbane:
    qubits: 127
    processor: "Eagle r3"
    queue_length: 2068
    recommended_for: ["large_proteins", "production_runs"]

languages:
  julia:
    role: "main_computation"
    description: "Quantum-classical hybrid protein folding pipeline"
    port: null
    status: "active"

  crystal:
    role: "quantum_server"
    description: "High-performance quantum TCP server"
    port: 8080
    status: "active"

  python:
    role: "async_wrapper"
    description: "Asynchronous wrapper and classical fallback"
    port: 8000
    status: "active"

  erlang:
    role: "distributed_actors"
    description: "Fault-tolerant distributed quantum job management"
    port: null
    status: "ready"

  chapel:
    role: "parallel_compute"
    description: "High-performance parallel quantum simulations"
    port: null
    status: "ready"

  agda:
    role: "formal_verification"
    description: "Type-level verification of quantum algorithms"
    port: null
    status: "ready"

  coq:
    role: "mathematical_proofs"
    description: "Formal mathematical verification"
    port: null
    status: "ready"

  balsa:
    role: "hardware_design"
    description: "Asynchronous hardware circuit design"
    port: null
    status: "ready"

protein_folding:
  max_sequence_length: 4000
  quantum_qubits_per_residue: 3
  classical_fallback: true
  timeout_seconds: 300

algorithms:
  grover_iterations: "pi/4 * sqrt(2^n)"
  vqe_depth: 3
  qft_precision: 8
  error_correction: "surface_code"

networking:
  bind_address: "0.0.0.0"
  quantum_server_port: 8080
  classical_server_port: 8000
  websocket_port: 8081

logging:
  level: "info"
  quantum_jobs: true
  performance_metrics: true
  error_tracking: true

# =======================================================================


# =======================================================================
